queue: Hosted Ubuntu 1604

pr:
  branches:
    include:
    - master
  paths:
    include:
    - kudulite/*
    - test/kudulite*

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - kudulite/*
    - test/kudulite*

steps:
- bash: |
    # login
    set -e
    echo $pswd | docker login -u $(dockerUsername) --password-stdin azurefunctions.azurecr.io

  displayName: login to registry
  continueOnError: false
  env:
    pswd: $(dockerPassword)

- bash: |
    set -e
    export CI_RUN=1
    export RUN_TESTS=1
    export namespace=$(namespace)
    export branch=$(branch)
    export tag=$(tag)
    export storageAccountName=$(storageAccountName)
    export storageAccountKey=$(storageAccountKey)
    export siteRestrictedToken=$(siteRestrictedToken)
    export v2RuntimeVersion=$(v2RuntimeVersion)
    export v3RuntimeVersion=$(v3RuntimeVersion)
    chmod +x ./kudulite/build.sh
    ./kudulite/build.sh
  displayName: build images
  continueOnError: false
