queue: Hosted Ubuntu 1604
trigger: none
variables:
  dockerId: azurefunctions

steps:
- bash: |
    # login
    echo $pswd | docker login -u $(dockerId) --password-stdin $(dockerId).azurecr.io
  displayName: login
  continueOnError: false
  env:
    pswd: $(dockerPassword)

- bash: |
    # pull
    set -e

    images=( base dotnet node python powershell )
    for i in "${images[@]}"
    do
      # Pull
      docker pull $(dockerId).azurecr.io/public/azure-functions/$i:$(ReleaseVersion)
      if [ "$i" != "base" ]; then
        docker pull $(dockerId).azurecr.io/public/azure-functions/$i:$(ReleaseVersion)-appservice
      fi

      # tag
      docker tag $(dockerId).azurecr.io/public/azure-functions/$i:$(ReleaseVersion) $(dockerId).azurecr.io/public/azure-functions/$i:2.0
      docker tag $(dockerId).azurecr.io/public/azure-functions/$i:$(ReleaseVersion) $(dockerId).azurecr.io/public/azure-functions/$i:latest
      docker tag $(dockerId).azurecr.io/public/azure-functions/$i:$(ReleaseVersion) $(dockerId).azurecr.io/public/azure-functions/$i:2.0-iot-edge

      if [ "$i" != "base" ]; then
        docker tag $(dockerId).azurecr.io/public/azure-functions/$i:$(ReleaseVersion)-appservice $(dockerId).azurecr.io/public/azure-functions/$i:2.0-appservice
      fi

      # Push
      docker push $(dockerId).azurecr.io/public/azure-functions/$i:2.0
      docker push $(dockerId).azurecr.io/public/azure-functions/$i:latest
      docker push $(dockerId).azurecr.io/public/azure-functions/$i:2.0-iot-edge

      if [ "$i" != "base" ]; then
        docker push $(dockerId).azurecr.io/public/azure-functions/$i:2.0-appservice
      fi

    done

    images=( dotnet powershell java )
    for i in "${images[@]}"
    do
      # Pull
      docker pull $(dockerId).azurecr.io/public/azure-functions/$i:$(ReleaseVersion)-alpine

      # tag
      docker tag $(dockerId).azurecr.io/public/azure-functions/$i:$(ReleaseVersion)-alpine $(dockerId).azurecr.io/public/azure-functions/$i:2.0-alpine

      # Push
      docker push $(dockerId).azurecr.io/public/azure-functions/$i:2.0-alpine
    done
  displayName: pull images
  continueOnError: false