queue: Hosted Linux Preview
trigger: none
variables:
  dockerId: azurefunctions

steps:
- bash: |
    # login
    echo $(dockerPassword) | docker login -u $(dockerId) --password-stdin $(dockerId).azurecr.io
  displayName: login
  continueOnError: false

- bash: |
    # login
    echo  $(dockerHubPassword) | docker login -u $(dockerHubUserId) --password-stdin docker.io
  displayName: login docker hub
  continueOnError: false

- bash: |
    # pull
    images=( base dotnet node python )
    for i in "${images[@]}"
    do
      imageName=$i:$(ReleaseVersion)
      docker pull $(dockerId).azurecr.io/azure-functions/$imageName
    done
  displayName: pull images
  continueOnError: false

- bash: |
    # tag
    docker tag $(dockerId).azurecr.io/azure-functions/base:$(ReleaseVersion) microsoft/azure-functions-base:$(ReleaseVersion)

    docker tag $(dockerId).azurecr.io/azure-functions/dotnet:$(ReleaseVersion) microsoft/azure-functions-dotnet-core2.0:$(ReleaseVersion)
    
    docker tag $(dockerId).azurecr.io/azure-functions/node:$(ReleaseVersion) microsoft/azure-functions-node8:$(ReleaseVersion)
    
    docker tag $(dockerId).azurecr.io/azure-functions/python:$(ReleaseVersion) microsoft/azure-functions-python3.6:$(ReleaseVersion)
  displayName: tag images
  continueOnError: false

- bash: |
    # push
    images=( "base" "dotnet-core2.0" "node8" "python3.6" )
    for i in "${images[@]}"
    do
      docker push microsoft/azure-functions-$i:$(ReleaseVersion)
    done
  displayName: push images
  continueOnError: false
