queue: Hosted Linux Preview
trigger: none
variables:
  dockerId: azurefunctions

steps:
- bash: |
    # login
    echo $pswd | docker login -u $(dockerId) --password-stdin $(dockerId).azurecr.io
  displayName: login
  continueOnError: false
  env:
    pswd: $(dockerPassword)

- bash: |
    # pull
    set -e
    images=( base dotnet node python powershell )
    for i in "${images[@]}"
    do
      docker pull $(dockerId).azurecr.io/public/azure-functions/$i:$(ReleaseVersion)
    done
  displayName: pull images
  continueOnError: false

- bash: |
    # tag
    set -e
    images=( base dotnet node python powershell )
    for i in "${images[@]}"
    do
      docker tag $(dockerId).azurecr.io/public/azure-functions/$i:$(ReleaseVersion) $(dockerId).azurecr.io/public/azure-functions/$i:2.0
      docker tag $(dockerId).azurecr.io/public/azure-functions/$i:$(ReleaseVersion) $(dockerId).azurecr.io/public/azure-functions/$i:latest
    done
  displayName: tag images
  continueOnError: false

- bash: |
    # push
    set -e
    images=( base dotnet node python powershell )
    for i in "${images[@]}"
    do
      docker push $(dockerId).azurecr.io/public/azure-functions/$i:2.0
      docker push $(dockerId).azurecr.io/public/azure-functions/$i:latest
    done
  displayName: push images
  continueOnError: false
