queue: Hosted Ubuntu 1604
trigger: none

steps:
  - bash: |
      echo $pswd | docker login -u $(dockerUsername) --password-stdin azurefunctions.azurecr.io
    displayName: login
    continueOnError: false
    env:
      pswd: $(dockerPassword)

  - bash: |
      set -e
      SOURCE_REGISTRY=azurefunctions.azurecr.io/azure-functions/3.0
      TARGET_REGISTRY=azurefunctions.azurecr.io/public/azure-functions

      if [ -z "$(TargetVersion)" ]; then
        echo "ERROR: TargetVersion is required"
        exit 1
      fi

      if [ -z "$(PrivateVersion)" ]; then
        echo "ERROR: PrivateVersion is required"
        exit 1
      fi

      echo "##vso[task.setvariable variable=SOURCE_REGISTRY]$SOURCE_REGISTRY"
      echo "##vso[task.setvariable variable=TARGET_REGISTRY]$TARGET_REGISTRY"
    displayName: set env
    continueOnError: false


  - bash: |
      set -e
      docker pull $SOURCE_REGISTRY/java:$(PrivateVersion)-java11
      docker pull $SOURCE_REGISTRY/java:$(PrivateVersion)-java11-slim
      docker pull $SOURCE_REGISTRY/java:$(PrivateVersion)-java11-appservice
      docker pull $SOURCE_REGISTRY/java:$(PrivateVersion)-java11-core-tools

      docker pull mcr.microsoft.com/java/maven:11-zulu-debian10

      docker tag $SOURCE_REGISTRY/java:$(PrivateVersion)-java11 $TARGET_REGISTRY/java:$(TargetVersion)-java11
      docker tag $SOURCE_REGISTRY/java:$(PrivateVersion)-java11-slim $TARGET_REGISTRY/java:$(TargetVersion)-java11-slim
      docker tag $SOURCE_REGISTRY/java:$(PrivateVersion)-java11-appservice $TARGET_REGISTRY/java:$(TargetVersion)-java11-appservice
      docker tag $SOURCE_REGISTRY/java:$(PrivateVersion)-java11-appservice $TARGET_REGISTRY/java:$(TargetVersion)-java11-appservice-quickstart
      docker tag $SOURCE_REGISTRY/java:$(PrivateVersion)-java11-core-tools $TARGET_REGISTRY/java:$(TargetVersion)-java11-core-tools

      docker tag mcr.microsoft.com/java/maven:11-zulu-debian10 $TARGET_REGISTRY/java:$(TargetVersion)-java11-build

      docker push $TARGET_REGISTRY/java:$(TargetVersion)-java11
      docker push $TARGET_REGISTRY/java:$(TargetVersion)-java11-slim
      docker push $TARGET_REGISTRY/java:$(TargetVersion)-java11-appservice
      docker push $TARGET_REGISTRY/java:$(TargetVersion)-java11-appservice-quickstart
      docker push $TARGET_REGISTRY/java:$(TargetVersion)-java11-core-tools

      docker push $TARGET_REGISTRY/java:$(TargetVersion)-java11-build

      docker system prune -a -f
    displayName: tag and push java images
    continueOnError: false


