queue: Hosted Ubuntu 1604

pr:
  branches:
    include:
      - master
  paths:
    include:
      - host/3.0/buster/amd64/python/*

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - host/3.0/buster/amd64/python/*

steps:
  - bash: |
      # login
      set -e
      echo $pswd | docker login -u $(dockerUsername) --password-stdin azurefunctions.azurecr.io

    displayName: login to registry
    continueOnError: false
    env:
      pswd: $(dockerPassword)

  - bash: |
      set -e
      IMAGE_NAME=azurefunctions.azurecr.io/azure-functions/3.0/python:$(Build.SourceBranchName)-python3.8-core-tools

      docker build -t $IMAGE_NAME \
                  -f host/3.0/buster/amd64/python/python38/python38-core-tools.Dockerfile \
                  host/3.0/buster/amd64/python/python38/
      npm run test $IMAGE_NAME --prefix  test/
      docker push $IMAGE_NAME
    displayName: python3.8-core-tools
    continueOnError: false
